name: ci.yml
on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Create cache directories
        run: |
          mkdir -p storage bootstrap/cache
          chmod -R 777 storage bootstrap/cache

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run PHPUnit
        run: php artisan test

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
