name: ci.yml
on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Create cache directories
        run: |
          mkdir -p storage bootstrap/cache storage/framework/views
          chmod -R 777 storage bootstrap/cache

      - name: Create testing environment file
        run: |
          cp .env.example .env.testing
          echo "VIEW_CACHE_PATH=storage/framework/views" >> .env.testing

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --dev && composer require --dev phpstan/phpstan larastan/larastan

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: |
          php artisan key:generate
          php artisan key:generate --env=testing
          cat .env | grep APP_KEY

      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run PHPUnit
        run: php artisan test

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
